# Generated by Django 5.0.6 on 2024-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_code', models.CharField(max_length=50, null=True)),
                ('institution_code', models.CharField(max_length=50, null=True)),
                ('institution', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
